### ISSUE TITLE
Chapter07/example1.py has some logic issues

### ISSUE THREAD

**Issue by 4honor** [PacktPublishing/Mastering-Concurrency-in-Python#1]
# Problem
The code in the consumer class doesn't guarantee that **although the queue has more than two elements, a single consumer can get all the two element**. Because other consumers will compete for these elements too, which will often result in a situation that the two elements are got by two different consumers, therefore making the control variable `result_size` work in an unexpected manner.

# Solution
Add a lock when get element from queue.
```python
lock = multiprocessing.Lock()

class ReductionConsumer(multiprocessing.Process):
    def __init__(self, task_queue, result_queue):
         ...

    def run(self):
        pname = self.name
        print("Using process %s..." % pname)

        while True:
            with lock:
                num1 = self.task_queue.get()
                ...
                self.task_queue.task_done()
                self.result_queue.put(num1 + num2)

**Comment by gaurav-packt** [comment]
Closing the issue with respect to the feedback shared by the user
