### ISSUE TITLE
Potential Issue with Example5 and 6 Chapter08

### ISSUE THREAD

**Issue by hassanaqeelkhan** [PacktPublishing/Mastering-Concurrency-in-Python#2]
Hi There,

I tried out examples 05 and 06 from Chapter08 of the book. Both of them run error-free. However, I don't observer any speed-up in Example-06. In fact example06 is slower. Outputs from both examples are below. I am using a Spyder4.0.1 IDE with Python version 3.7.6 on a windows-10 machine with 12 cores. Would appreciate any pointers on how this issue can be resolved.

============Example05.py output====================
Took 1.2080 seconds with 1 process(es).
Took 1.1229 seconds with 2 process(es).
Took 0.9995 seconds with 3 process(es).
Took 1.0282 seconds with 4 process(es).
Took 1.0535 seconds with 5 process(es).
Took 1.0578 seconds with 6 process(es).
Done.

============Example06.py output====================
Took 1.4141 seconds with 1 process(es).
Took 1.1089 seconds with 2 process(es).
Took 1.0429 seconds with 3 process(es).
Took 1.0382 seconds with 4 process(es).
Took 1.0399 seconds with 5 process(es).
Took 1.0465 seconds with 6 process(es).
Done.

**Comment by hassanaqeelkhan** [comment]
[Update] I went through the code again. I think this behavior can change from one machine to another (depending on number of cores and clock speed). I added a little bit of a delay in the process_threshold( ) function and that does demonstrate improvement in speed when extra cores are used. It looks like I wasn't observing any increase in speed previously because, the image processing task is too simple and completes just too quickly. Here is what I observe if I add a delay of 0.05 seconds using the time.delay(0.05) function in example6.py. I also increased the max number of processes to 11.

Took 25.3112 seconds with 1 process(es).
Took 12.9302 seconds with 2 process(es).
Took 8.8643 seconds with 3 process(es).
Took 6.5656 seconds with 4 process(es).
Took 5.3609 seconds with 5 process(es).
Took 4.6086 seconds with 6 process(es).
Took 4.1803 seconds with 7 process(es).
Took 3.7594 seconds with 8 process(es).
Took 3.5207 seconds with 9 process(es).
Took 2.9801 seconds with 10 process(es).
Took 3.0996 seconds with 11 process(es).
Done.


Although, the changes I introduced are trivial, I am leaving my version of example6 below.

#Chapter08/example6.py
from multiprocessing import Pool
import cv2

import sys
from functools import partial
from timeit import default_timer as timer
import time


THRESH_METHOD = cv2.ADAPTIVE_THRESH_GAUSSIAN_C
INPUT_PATH = 'input/large_input/'
OUTPUT_PATH = 'output/large_output/'

n = 20
names = ['ship_%i_%i.jpg' % (i, j) for i in range(n) for j in range(n)]


def process_threshold(name, thresh_method):
    im = cv2.imread(INPUT_PATH + name)
    gray_im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    thresh_im = cv2.adaptiveThreshold(gray_im, 255, thresh_method, cv2.THRESH_BINARY, 11, 2)

    cv2.imwrite(OUTPUT_PATH + name, thresh_im)
    time.sleep(0.05)

if __name__ == '__main__':

    for n_processes in range(1, 12):
        start = timer()

        with Pool(n_processes) as p:
            p.map(partial(process_threshold, thresh_method=THRESH_METHOD), names)

        print('Took %.4f seconds with %i process(es).' % (timer() - start, n_processes))
        
    print('Done.')

**Comment by KrisNguyen135** [comment]
Hello,

Thanks for the issue and the comment!

I think your insight is correct, and the reason I observed a speedup in the original code is because I was running it on a computer with less compute, so the improvement was more obvious.

Please feel free to reopen this or open a new issue if you run into another problem!
